export const products = [
	{
		id: '1',
		name: 'Ustun',
		img: '/assets/kolizeykolonna2.png',
		value: 'ustun',
	},
	{
		id: '2',
		name: 'Ustun',
		img: '/assets/kolizeykolonna1.png',
		value: 'skameyka',
		defination: 'kolizey ustuni',
	},
	{
		id: '3',
		name: 'Ustun',
		img: '/assets/kolizeykolonna3.png',
		value: 'regel',
		defination: 'kolizey ustuni regel',
	},
	{
		id: '4',
		name: 'Ustun',
		img: '/assets/kolizeykolonna4.png',
		value: 'stakan',
		defination: 'kolizey ustuni stakan',
	},
	{
		id: '5',
		name: 'Ustun',
		img: '/assets/kolizeyKOLONNA5.png',
		value: 'ustun',
		defination: 'kolizey ustuni kolonna 5',
	},
	{
		id: '6',
		name: 'Ustun',
		img: '/assets/kolizeybalyasina.png',
		value: 'balyasina',
		defination: 'kolizey ustuni balyasina',
	},
	{
		id: '7',
		name: 'Ustun',
		img: '/assets/kolizeybalyasina1.png',
		value: 'balyasina',
		defination: 'kolizey ustuni balyasina 1',
	},
	{
		id: '8',
		name: 'Ustun',
		img: '/assets/kolizeybalyasina2.png',
		value: 'balyasina',
		defination: 'kolizey ustuni balyasina 2',
	},
]
